import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import { Footer } from '@/components/Footer';
import Modal from '@/components/Modals/Modal';
import RegisterModal from '@/components/Modals/RegisterModal';

import RentModal from '@/components/Modals/RentModal';
import { Navbar } from '@/components/Navbar/Navbar';
import ClientCompopnent from '@/layouts/ClientComponent';


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientCompopnent>
          <Navbar />
          <RegisterModal />
          <RentModal />
          <div className='pb-20 pt-40'>
            {children}
          </div>
          <Footer />
        </ClientCompopnent>
      </body>
    </html>
  );
}
