import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import Modal from '@/components/Modals/Modal';
import RegisterModal from '@/components/Modals/RegisterModal';

import ClienComp from '@/components/ClienComp';
import RentModal from '@/components/Modals/RentModal';


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClienComp>
          <Header />
          <RegisterModal />
          <RentModal />
          <div className='pb-20 pt-20'>
            {children}
          </div>
          <Footer />
        </ClienComp>
      </body>
    </html>
  );
}
